#!/bin/sh
set -e

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    update-desktop-database /usr/share/applications 2>/dev/null || true
    gtk-update-icon-cache /usr/share/icons/hicolor 2>/dev/null || true
fi

if [ "$1" = "purge" ]; then
    rm -rf ~/.config/autostart/httransfer.desktop 2>/dev/null || true
    rm -rf ~/.local/share/HunterTransfer 2>/dev/null || true
fi

exit 0